options:
  dcf_path: "@BUS_CONFIG_PATH@"

master:
  node_id: 1
  driver: "ros2_canopen::MasterDriver"
  package: "canopen_master_driver"
  baudrate: 500000
  sync_period: 10000 # us
  start: true
  start_nodes: true
  start_all_nodes: true
  boot_time: 1000
  boot_timeout: 1000

defaults:
  product_code: 0
  dcf: "ardagvmotor.eds"
  driver: "ros2_canopen::Cia402Driver"
  package: "canopen_402_driver"
  period: 10 # ms
  heartbeat_producer: 100 # Heartbeat every 100 ms
  boot: false
  mandatory: true
  velocity_mode: 3
  sdo: # SDO executed during config
    - { index: 0x1017, sub_index: 0, value: 500 } # Heartbeat every 500ms
  tpdo:
    1:
      enabled: false # XXX
      cob_id: "auto"
      mapping:
        - {index: 0x6041, sub_index: 0} # status word
    2:
      enabled: true
      cob_id: "auto"
      mapping:
        - {index: 0x6041, sub_index: 0} # status word
        - {index: 0x6061, sub_index: 0} # modes of operation display
    3:
      enabled: true
      cob_id: "auto"
      mapping:
        - {index: 0x6041, sub_index: 0} # status word
        - {index: 0x6064, sub_index: 0} # position actual value
    4:
      enabled: true
      cob_id: "auto"
      mapping:
        - {index: 0x6041, sub_index: 0} # status word
        - {index: 0x606C, sub_index: 0} # velocity actual value
  rpdo:
    1:
      enabled: false # XXX
      cob_id: "auto"
      mapping:
        - {index: 0x6040, sub_index: 0} # controlword
    2:
      enabled: true
      cob_id: "auto"
      mapping:
        - {index: 0x6040, sub_index: 0} # controlword
        - {index: 0x6060, sub_index: 0} # Modes of operation
    3:
      enabled: false
      cob_id: "auto"
      mapping:
        - {index: 0x6040, sub_index: 0} # controlword
    4:
      enabled: true
      cob_id: "auto"
      mapping:
        # XXX - {index: 0x6040, sub_index: 0} # controlword
        - {index: 0x60FF, sub_index: 0} # target velocity
nodes:
  ardagv_motor_left:
    node_id: 0x16
    scale_pos_to_dev: -521519.0
    scale_vel_to_dev: -221207.0
    scale_pos_from_dev: -1.917475982666016e-06
    scale_vel_from_dev: -4.712388975e-06

  ardagv_motor_right:
    node_id: 0x14
    scale_pos_to_dev: 521519.0
    scale_vel_to_dev: 221207.0
    scale_pos_from_dev: 1.917475982666016e-06
    scale_vel_from_dev: 4.712388975e-06

