<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="inertial_macros.xacro"/>

    <xacro:property name="chassis_length" value="0.60"/>
    <xacro:property name="chassis_width" value="0.30"/>
    <xacro:property name="chassis_height" value="0.15"/>
    <xacro:property name="base_width" value="0.22"/>
    <xacro:property name="chassis_zoff" value="0.08"/>
    <xacro:property name="chassis_mass" value="1.0"/>

    <xacro:property name="wheel_radius" value="0.05"/>
    <xacro:property name="wheel_width" value="0.025"/>
    <xacro:property name="wheel_mass" value="0.05"/>

    <xacro:property name="caster_wheel_radius" value="0.025"/>
    <xacro:property name="caster_wheel_mass" value="0.01"/>
    <xacro:property name="caster_wheel_zoff" value="${caster_wheel_radius}"/>

    <material name="cyan"><color rgba="0 1.0 1.0 1.0"/></material>
    <material name="gray"><color rgba="0.5 0.5 0.5 1.0"/></material>
    <material name="white"><color rgba="1 1 1 1"/></material>
    <material name="orange"><color rgba="1 0.3 0.1 1"/></material>
    <material name="blue"><color rgba="0.2 0.2 1 1"/></material>
    <material name="black"><color rgba="0 0 0 1"/></material>
    <material name="red"><color rgba="1 0 0 1"/></material>

    <!-- BASE LINK -->

    <link name="base_link"></link>

    <!-- BASE_FOOTPRINT LINK -->

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint"></link>

    <!-- CHASSIS LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="0 0 ${chassis_zoff}"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="0 0 ${chassis_zoff}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="cyan"/>
        </visual>
        <collision>
            <origin xyz="0 0 ${chassis_zoff}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="0 0 ${chassis_zoff}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/Gray</material>
    </gazebo>

    <!-- LEFT WHEEL LINK -->

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${(base_width + wheel_width)/2} ${wheel_radius}" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_width}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <!-- RIGHT WHEEL LINK -->

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 ${-(base_width + wheel_width)/2} ${wheel_radius}" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_width}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <!-- CASTER WHEEL LINKS -->
    <xacro:macro name="caster_wheel" params="prefix x_reflect y_reflect">
        <link name="${prefix}_link">
            <visual>
                <geometry>
                    <sphere radius="${caster_wheel_radius}"/>
                </geometry>
                <material name="cyan"/>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <sphere radius="${caster_wheel_radius}"/>
                </geometry>
            </collision>
            <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:inertial_sphere>
        </link>

        <joint name="${prefix}_joint" type="fixed">
            <parent link="base_link"/>
            <child link="${prefix}_link"/>
            <origin xyz="${x_reflect*(chassis_length/2-caster_wheel_radius)} ${y_reflect*(base_width/2-caster_wheel_radius)} ${caster_wheel_zoff}" rpy="0 0 0"/>
        </joint>

        <gazebo reference="${prefix}_link">
            <material>Gazebo/Blue</material>
            <mu1 value="0.001"/>
            <mu2 value="0.001"/>
        </gazebo>
    </xacro:macro>

    <xacro:caster_wheel prefix="front_left_caster" x_reflect="1" y_reflect="1"/>
    <xacro:caster_wheel prefix="front_right_caster" x_reflect="1" y_reflect="-1"/>
    <xacro:caster_wheel prefix="rear_left_caster" x_reflect="-1" y_reflect="1"/>
    <xacro:caster_wheel prefix="rear_right_caster" x_reflect="-1" y_reflect="-1"/>

</robot>
