controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # Either the differential drive or the forward command controller will be spawned, it doesn't make much sense to use both at once. The two launch files only differ in which one they launch.
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    forward_velocity_controller:
      type: forward_command_controller/ForwardCommandController

forward_velocity_controller:
  ros__parameters:
    joints:
      - wheel_left
      - wheel_right
    interface_name: velocity

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["wheel_left"]
    right_wheel_names: ["wheel_right"]
    interface_name: velocity

    wheel_separation: 0.3 # TODO
    wheel_radius: 0.05 # TODO

    # position_feedback: true # TODO(ioan): do we actually have usable position feedback?

