amcl:
  ros__parameters:
    # https://docs.nav2.org/configuration/packages/configuring-amcl.html
    
    alpha1: 0.1 # rad/s -> rad/s, covariance from rotation to rotation
    alpha2: 0.05 # rad/s -> m/s, covariance from translation to rotation
    alpha3: 0.05 # m/s -> rad/s, covariance from rotation to translation
    alpha4: 0.05 # m/s -> m/s, covariance from translation to translation
    # alpha5 irrelevant for diff drive
    
    update_min_a: 0.2 # 10deg per update
    update_min_d: 0.03 # 3cm per update

    #pf_z: .5
    #pf_err: 0.5

    recovery_alpha_fast: 0.1
    recovery_alpha_slow: 0.001

    sigma_hit: 0.05 # 5cm stddev on distances
    z_hit: 0.5
    z_rand: 0.5

    set_initial_pose: True
    initial_pose:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0

    base_frame_id: base_link
    global_frame_id: map
    odom_frame_id: odom
    scan_topic: /cam1/scan


    do_beamskip: false
    beam_skip_distance: 0.05
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3

    laser_likelihood_max_dist: 0.1 # 10cm bubble around obstacles

    laser_model_type: likelihood_field

    max_beams: 360
    max_particles: 200
    min_particles: 50

local_costmap:
  local_costmap:
    ros__parameters:
      footprint: "[ [0.30, -0.15], [-0.30, -0.15], [-0.30, 0.15], [0.30, 0.15] ]" # updated footprint


global_costmap:
  global_costmap:
    ros__parameters:
      footprint: "[ [0.30, -0.15], [-0.30, -0.15], [-0.30, 0.15], [0.30, 0.15] ]" # updated footprint

map_server:
  ros__parameters:
    use_sim_time: False
    yaml_filename: "/home/runner/ros2_ws/src/ardagv/config/map.yaml"

