controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # When launching just_motors.launch.py, choose between 'controller:=diff_drive_controller' (default) and 'controller:=forward_velocity_controller', or another controller you may add here.
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

#   forward_velocity_controller:
#     type: forward_command_controller/ForwardCommandController

# forward_velocity_controller:
#   ros__parameters:
#     joints:
#       - motor_left
#       - motor_right
#     interface_name: velocity

diff_drive_controller:
  ros__parameters:
    #publish_rate: 50.0

    base_frame_id: base_link
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    interface_name: velocity

    # Update with your robot's measurements
    wheel_separation: 0.27
    wheel_radius: 0.05

    position_feedback: true
    enable_odom_tf: true # set to False when using EKF odom tf
    use_stamped_vel: false

    pose_covariance_diagonal: [0.005, 0.005, 0.0, 0.0, 0.0, 0.001]
    twist_covariance_diagonal: [0.005, 0.005, 0.0, 0.0, 0.0, 0.001]

    # open_loop: false    

    # wheels_per_side: x
    # wheel_separation_multiplier: x
    # left_wheel_radius_multiplier: x
    # right_wheel_radius_multiplier: x

    # odom_frame_id: x
    # pose_covariance_diagonal: x
    # twist_covariance_diagonal: x
    # open_loop: x
    # enable_odom_tf: x

    # cmd_vel_timeout: x
    # publish_limited_velocity: x
    # velocity_rolling_window_size: x
    

    # linear.x.has_velocity_limits: false
    # linear.x.has_acceleration_limits: false
    # linear.x.has_jerk_limits: false
    # linear.x.max_velocity: NAN
    # linear.x.min_velocity: NAN
    # linear.x.max_acceleration: NAN
    # linear.x.min_acceleration: NAN
    # linear.x.max_jerk: NAN
    # linear.x.min_jerk: NAN

    # angular.z.has_velocity_limits: false
    # angular.z.has_acceleration_limits: false
    # angular.z.has_jerk_limits: false
    # angular.z.max_velocity: NAN
    # angular.z.min_velocity: NAN
    # angular.z.max_acceleration: NAN
    # angular.z.min_acceleration: NAN
    # angular.z.max_jerk: NAN
    # angular.z.min_jerk: NAN




# joint_state_broadcaster:
#   ros__parameters:

