ardagv_controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # When launching just_motors.launch.py, choose between 'controller:=diff_drive_controller' (default) and 'controller:=forward_velocity_controller', or another controller you may add here.
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    forward_velocity_controller:
      type: forward_command_controller/ForwardCommandController

forward_velocity_controller:
  ros__parameters:
    joints:
      - motor_left
      - motor_right
    interface_name: velocity

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["motor_left"]
    right_wheel_names: ["motor_right"]
    interface_name: velocity

    # Update with your robot's measurements
    wheel_separation: 0.27
    wheel_radius: 0.05

    position_feedback: false # TODO(ioan): do we actually have usable position feedback?

