twist_mux:
  ros__parameters:
    topics:
      joy:
        topic: cmd_vel_joy
        timeout: 0.1
        priority: 50
      nav:
        topic: cmd_vel_nav
        timeout: 0.1
        priority: 30
    locks:
      killswitch:
        topic: killswitch
        timeout: 0.0
        priority: 255
